spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employer_auth_service_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
jwt:
  secret: MySuperStrongSecretKeyThatIsAtLeast32CharactersLong!
  issuer: employer_auth-service
  expiration: 3600000    
